/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
package to_dl_analytics

import org.apache.spark.sql.SparkSession

object App {
  def main(args: Array[String]): Unit = {

    val session = SparkSession.builder
      .appName("to_dl_analytics")
      .enableHiveSupport()
      .getOrCreate()

    session.sparkContext.setLogLevel("Warn")

  }
}
