package to_dl_analytics

case class Record(
c_id:Int,                               //"SK_ID_CURR"
f_target:Int,                           //"TARGET"
c_contract:Int,                         //"NAME_CONTRACT_TYPE"
c_gender_t:Int,                         //"CODE_GENDER"
f_car:Int,                              //"FLAG_OWN_CAR"
f_realty:Int,                           //"FLAG_OWN_REALTY"
a_children:Int,                         //"CNT_CHILDREN"
a_income:Int,                           //"AMT_INCOME_TOTAL"
a_credit:Int,                           //"AMT_CREDIT"
a_annuity:Int,                          //"AMT_ANNUITY"
a_goods_price:Int,                      //"AMT_GOODS_PRICE"
c_accomplice:Int,                       //"NAME_TYPE_SUITE"
c_income:Int,                           //"NAME_INCOME_TYPE"
c_education:Int,                        //"NAME_EDUCATION_TYPE"
c_family:Int,                           //"NAME_FAMILY_STATUS"
c_housing:Int,                          //"NAME_HOUSING_TYPE"
a_reg:Int,                              //"REGION_POPULATION_RELATIVE"
d_birth:Int,                            //"DAYS_BIRTH"
d_employed:Int,                         //"DAYS_EMPLOYED"
d_reg:Int,                              //"DAYS_REGISTRATION"
d_id:Int,                               //"DAYS_ID_PUBLISH"
d_car:Int,                              //"OWN_CAR_AGE"
f_mobile:Int,                           //"FLAG_MOBIL"
f_cont:Int,                             //"FLAG_CONT_MOBILE"
f_email:Int,                            //"FLAG_EMAIL"
c_occup:Int,                            //"OCCUPATION_TYPE"
a_family:Int,                           //"CNT_FAM_MEMBERS"
r_reg:Int,                              //"REGION_RATING_CLIENT"
r_reg_city:Int,                         //"REGION_RATING_CLIENT_W_CITY"
s_dow:Int,                              //"WEEKDAY_APPR_PROCESS_START"
s_hour:Int,                             //"HOUR_APPR_PROCESS_START",
f_adress_not_match_cont_adress:Int,     //"REG_REGION_NOT_LIVE_REGION"
f_adress_not_match_work_adress:Int      //"REG_REGION_NOT_WORK_REGION"
)

//K_Id:Int,                             //"SK_ID_CURR"
//Flagged:Int,                          //"TARGET"
//OwnsCar:Int,                          //"FLAG_OWN_CAR"
//OwnsRealty:Int,                       //"FLAG_OWN_REALTY"
//Children:Int,                         //"CNT_CHILDREN"
//TotalIncome:Int,                      //"AMT_INCOME_TOTAL"
//CreditAmount:Int,                     //"AMT_CREDIT"
//AnnuityAmount:Int,                    //"AMT_ANNUITY"
//CreditGoodsPrice:Int,                 //"AMT_GOODS_PRICE"
//IncomeType:Int,                       //"NAME_INCOME_TYPE"
//RegionPopulation:Int,                 //"REGION_POPULATION_RELATIVE"
//AgeInDays:Int,                        //"DAYS_BIRTH"
//DaysEmployed:Int,                     //"DAYS_EMPLOYED"
//DaysRegistered:Int,                   //"DAYS_REGISTRATION"
//DaysIdChanged:Int,                    //"DAYS_ID_PUBLISH"
//CarAgeInDays:Int,                     //"OWN_CAR_AGE"
//HasMobilePhone:Int,                   //"FLAG_MOBIL"
//MobileAvailable:Int,                  //"FLAG_CONT_MOBILE"
//HasEmail:Int,                         //"FLAG_EMAIL"
//FamilyAmount:Int,                     //"CNT_FAM_MEMBERS"
//RegionRating:Int,                     //"REGION_RATING_CLIENT"
//RegionCityRating:Int,                 //"REGION_RATING_CLIENT_W_CITY"
//TimeInHoursApplied:Int,               //"HOUR_APPR_PROCESS_START",
//AdressDoesntMatchContactAdress:Int,   //"REG_REGION_NOT_LIVE_REGION"
//AdressDoesntMatchWorkAdress:Int,      //"REG_REGION_NOT_WORK_REGION"
//ContractType:Int,                     //"NAME_CONTRACT_TYPE"
//Gender:Int,                           //"CODE_GENDER"
//Accomplice:Int,                       //"NAME_TYPE_SUITE"
//EducationType:Int,                    //"NAME_EDUCATION_TYPE"
//FamilyStatus:Int,                     //"NAME_FAMILY_STATUS"
//HousingType:Int,                      //"NAME_HOUSING_TYPE"
//OccupationType:Int,                   //"OCCUPATION_TYPE"
//DayOfWeekApplied:Int                  //"WEEKDAY_APPR_PROCESS_START"


// 9 dictionaries:

// ContractType, Gender, Accomplice, IncomeType, EducationType,
// FamilyStatus, HousingType, OccupationType, DayOfWeekApplied