/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Scala library project to get you started.
 * For more details take a look at the Scala plugin chapter in the Gradle
 * User Manual available at https://docs.gradle.org/6.1/userguide/scala_plugin.html
 */

plugins {
    // Apply the scala plugin to add support for Scala
    scala

    // Apply the java-library plugin for API and implementation separation.
    `java-library`
}

repositories {
    // Use jcenter for resolving dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
}

dependencies {

    // Scala
    implementation("org.scala-lang:scala-library:2.12.10")

    // Spark hive
    implementation("org.apache.spark:spark-core_2.12:3.0.0-preview")
    implementation("org.apache.spark:spark-sql_2.12:3.0.0-preview")
    implementation("org.apache.spark:spark-hive_2.12:3.0.0-preview")
}


