/*
 * This Scala Testsuite was generated by the Gradle 'init' task.
 */
package to_dl_analytics

import org.scalatest.FunSuite
import org.junit.runner.RunWith
import org.scalatestplus.junit.JUnitRunner

@RunWith(classOf[JUnitRunner])
class AppSuite extends FunSuite {
  test("someLibraryMethod is always true") {

  }
}
